-- Packer
require('plugins')
-- Config
require('settings')
require('settings.color')
require('settings.font')
require('settings.completion')
require('settings.filetype')
-- LSP Config
require('lsp')
-- Plugins config
require('plugins.feline')
require('plugins.octo')
require('plugins.fterm')
require('plugins.hlslens')
require('plugins.treesitter')
require('plugins.colorizer')
require('plugins.gitsigns')
require('plugins.nvim-autopairs')
require('plugins.nvim-ts-rainbow')
require('plugins.nvimtree')
require('plugins.indent-blankline')
require('plugins.telescope')
require('plugins.numb')
require('plugins.nvim-notify')
require('plugins.which-key')
require('plugins.alpha-nvim')
require('plugins.ctrlsf')
require('plugins.editorconfig')
require('plugins.vim-gutentags')
require('plugins.vim-rooter')
require('plugins.vim-rubocop')
require('plugins.marks')
require('plugins.lightspeed')
require('plugins.lspkind')
require('plugins.neoscroll')
require('plugins.minimap')
require('plugins.todo-comments')
require('plugins.formatter')
require('plugins.stabilize')
require('plugins.nvim-neoclip')
require('plugins.nvim-gps')
require('plugins.copilot')
-- Keymap
require('settings.keymap')
