-- Packer
require('plugins')
-- Config
require('settings')
require('settings.completion')
require('settings.filetype')
require('settings.highlight')
require('settings.keymap')
-- LSP Config
require('lsp')
-- Plugins config
require('plugins.galaxyline')
require('plugins.treesitter')
require('plugins.colorizer')
require('plugins.lspfuzzy')
require('plugins.gitsigns')
require('plugins.nvim-autopairs')
require('plugins.nvim-ts-rainbow')
require('plugins.nvimtree')
require('plugins.indent-blankline')
require('plugins.telescope')
require('plugins.numb')
require('plugins.vim-startify')
require('plugins.ctrlsf')
require('plugins.editorconfig')
require('plugins.vim-gutentags')
require('plugins.vim-rooter')
require('plugins.vim-rubocop')
require('plugins.vim-signature')
require('plugins.vim-sneak')
