return {
  -- Colorschema
  'sainnhe/gruvbox-material',
  -- 'catppuccin/nvim', as = "catppuccin",
  -- 'olimorris/onedarkpro.nvim',
  -- 'folke/tokyonight.nvim',
  'MunifTanjim/nui.nvim',
  -- LSP
  'williamboman/mason.nvim',
  'williamboman/mason-lspconfig.nvim',
  'neovim/nvim-lspconfig',
  'onsails/lspkind-nvim',
  'weilbith/nvim-code-action-menu',
  -- Autocomplete
  'hrsh7th/nvim-cmp',
  'hrsh7th/cmp-nvim-lsp',
  'hrsh7th/cmp-buffer',
  'hrsh7th/cmp-vsnip',
  'hrsh7th/vim-vsnip',
  'hrsh7th/cmp-path',
  'hrsh7th/cmp-calc',
  'hrsh7th/cmp-cmdline',
  'ray-x/cmp-treesitter',
  'lukas-reineke/cmp-rg',
  'quangnguyen30192/cmp-nvim-tags',
  'rafamadriz/friendly-snippets',
  'windwp/nvim-autopairs',
  'windwp/nvim-ts-autotag',
  'andymass/vim-matchup',
  -- Treesitter
  'David-Kunz/markid',
  'nvim-treesitter/nvim-treesitter',
  'p00f/nvim-ts-rainbow',
  'lukas-reineke/indent-blankline.nvim',
  'JoosepAlviste/nvim-ts-context-commentstring',
  'lewis6991/nvim-treesitter-context',
  'SmiteshP/nvim-gps',
  -- Syntax
  'chrisbra/csv.vim',
  'junegunn/vim-easy-align',
  'mhartington/formatter.nvim',
  'zdharma-continuum/zinit-vim-syntax',
  'numToStr/Comment.nvim',
  -- Icons
  'nvim-tree/nvim-web-devicons',
  -- Status Line and Bufferline
  'famiu/feline.nvim',
  'kazhala/close-buffers.nvim',
  'noib3/nvim-cokeline',
  -- Telescope
  'nvim-lua/popup.nvim',
  'nvim-lua/plenary.nvim',
  'nvim-telescope/telescope.nvim',
  'nvim-telescope/telescope-fzy-native.nvim',
  'cljoly/telescope-repo.nvim',
  'nvim-telescope/telescope-dap.nvim',
  -- Explorer
  'kyazdani42/nvim-tree.lua',
  -- Color
  'nvchad/nvim-colorizer.lua',
  -- Git
  'lewis6991/gitsigns.nvim',
  'rhysd/committia.vim',
  -- Registers & clipboard
  'AckslD/nvim-neoclip.lua',
  -- Move & Search & replace
  'nacro90/numb.nvim',
  'kevinhwang91/nvim-hlslens',
  'ggandor/lightspeed.nvim',
  'karb94/neoscroll.nvim',
  'chaoren/vim-wordmotion',
  'windwp/nvim-spectre',
  'fedepujol/move.nvim',
  -- Tim Pope docet
  'tpope/vim-rails',
  'tpope/vim-abolish',
  'tpope/vim-sleuth',
  'tpope/vim-bundler',
  'tpope/vim-capslock',
  'tpope/vim-repeat',
  'tpope/vim-endwise',
  'tpope/vim-dispatch',
  'tpope/vim-dadbod',
  'tpope/vim-jdaddy',
  'tpope/vim-fugitive',
  -- Tmux
  'christoomey/vim-tmux-navigator',
  -- Tags
  'ludovicchabant/vim-gutentags',
  -- Debugger
  'mfussenegger/nvim-dap',
  'rcarriga/nvim-dap-ui',
  'theHamsta/nvim-dap-virtual-text',
  -- General Plugins
  'machakann/vim-sandwich',
  'rcarriga/nvim-notify',
  'folke/noice.nvim',
  'folke/trouble.nvim',
  'folke/todo-comments.nvim',
  'folke/which-key.nvim',
  'airblade/vim-rooter',
  'goolord/alpha-nvim',
  'jeffkreeftmeijer/vim-numbertoggle',
  'lambdalisue/suda.vim',
  'numtostr/FTerm.nvim',
  'wfxr/minimap.vim',
  'beauwilliams/focus.nvim',
  'kevinhwang91/nvim-bqf',
  -- 'dstein64/vim-startuptime',
}
